#!/usr/bin/env bash

export Dot="/afs/unity.ncsu.edu/users/$(echo $USER | cut -c 1)/$USER/.config"

_c0="\033[00m"     # white
_c1="\033[01;32m"  # green
_c2="\033[01;34m"  # blue
_c3="\033[31m"     # red
_c5="\033[35m"     # purple
_c6="\033[33m"     # yellow
_c7="\033[36m"     # turquoise

here() { cd $1; basename "$PWD"; }

PROMPT_COMMAND='echo -ne "$(hostname -s):${_c6}$(git branch 2>/dev/null | grep '^*' | colrm 1 2) \033]0;$(here ../..)/$(here ..)/$(here .)\007";PS1="${_c1}$(here ../..)/$_c2$(here ..)/$_c3$(here .) ${_c6}\!>${_c0}\e[m "'


alias egrep='egrep --color=auto'
alias eos="cd $Dot/.."
alias fgrep='fgrep --color=auto'
alias gc="git config credential.helper 'cache --timeout=3600'"
alias get='git pull'
alias grep='grep --color=auto'
alias ls='ls --color'
alias matrix="cmatrix -b -u 6"
alias mc='mc -x'
alias put='gc; git commit -am saving; git push; git status'
alias tmux="cd $Dot/..; tmux -f $Dot/dottmux"
alias vi="vim -u $Dot/dotvimrc"

bashing() {
  Bashrc=$Dot/dotbashrc
  There=$HOME/.bashrc
  (grep ". $Bashrc" $There || echo ". $Bashrc" >> $There )>/dev/null
}


export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS='--quit-if-one-screen --ignore-case --status-column --LONG-PROMPT --RAW-CONTROL-CHARS --HILITE-UNREAD --tabs=4 --no-init --window=-4 -R '
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\E[1;36m'     # begin blink
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

commit() {
	(cd $Dot/../gits/timm/dot/ncsu/vcl; make)
}
pathadd() {
      if  [[ ":$PATH:" != *":$1:"* ]]; then
          export PATH="${PATH:+"$PATH:"}$1"
      fi
}
pathadd ../bin
bashing
