#!/bin/bash

export  Dot="/afs/unity.ncsu.edu/users/$(echo $USER | cut -c 1)/$USER/.config"

main() {
  local files="tmix dotbashrc dotvimrc tmux-session1"
  local web='https://raw.githubusercontent.com/timm/dot/master/ncsu/vcl'
  local opt="/me/opt"
  local apts="vim aspell clisp ctags gawk gnuplot gnu-smalltalk haskell-platform pandoc htop luajit lua5.2 mc ncdu python-pip nodejs npm"
  local npms=""
      $get install nodejs npm
      $get install haskell-platform pandoc
0
  ## Usage: sudo tnix args   
  ##    or . tnix            <== takes you to your afs root
  
  
  ##         : with no arguments, takes you to $me
  if   [ -z "$1"           ]; then cd $me
  ## help    : show help
  elif [ "$1" == "help"    ]; then sed -n 's/^## //p' /bin/tnix
  ## email   : set git config user.eamil
  elif [ "$1" == "email"  ]; then shift; git config --global user.email "$*"
  ## email   : set git config user.name
  elif [ "$1" == "name"  ]; then shift; git config --global user.name "$*"
  elif [ "$1" == "install" ]; 
    mkdir -p $opt/julia
    mkdir -p $HOME/tmp
    mdkir -p $Dot
    local get="apt -qq -y "
    apt update
    apt upgrade -y
    apt install -y wget
    for f in $files; do
        if [ ! -f "$f" ]; then wget -O $f $web/$f;  fi
      done
    cp tnix /bin/tnix
    chmod +x /bin/tnix
    if [ ! -f "$opt/julia1.1.0.tar.gz" ]; then
       wget -O "$opt/julia1.1.0.tar.gz" https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.0-linux-x86_64.tar.gz
       tar xzf julia1.1.0.tar.gz
    fi
      (cd $HOME; sudo npm install -g typescript;  sudo npm install -g coffeescript)

      if [ ! `which pip` ]>&2; then
         curl https://bootstrap.pypa.io/get-pip.py -o $HOME/get-pip.py
         sudo python $HOME/get-pip.py
         rm $HOME/get-pip.py
      fi
      sudo -H pip install --upgrade pip
      $get install python3 swi-prolog tmux tree wget source-highlight
      # lit programming stuff
      sudo -H pip install pycco
    }
    
    fun() {
      $get  install bsdgames cmatrix
      if [ ! `which asciiquarium` ]>&2; then
        sudo add-apt-repository   -y ppa:ytvwld/asciiquarium > /dev/null
        $get update 
        $get install asciiquarium
      fi
    }
    
    vim8() {
      sudo add-apt-repository   -y ppa:jonathonf/vim > /dev/null
      $get update
      $get upgrade vim
    }
    
    vundle() {
      mkdir -p $Dot/tmp
      local d="$Dot/vim/bundle"
      if [ ! -d "$d" ]; then
        mkdir -p $d
        git clone https://github.com/gmarik/Vundle.vim.git $d
      fi
      vim -u "$Dot/dotvimrc" +PluginInstall +qall 
    }
    
    set -x
    #files; os;
    #lots; fun;
    #julia11
    #vim8; 
    vundle
    #sudo apt autoclean
    #sudo apt clean
    #sudo apt autoremove
    set +x 
  fi
}

main "$@"
